name: Progress Bar CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.5.3
    - name: Use Node.js
      uses: actions/setup-node@v3.7.0
      with:
        node-version: 18
    - name: Update README.md
      run: node index.js > README.md
    - name: Commit change & Push
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'zghy256+github-actions[bot]@users.noreply.github.com'
          git commit -am "bot: update README.md automatically"
          git push
